### ISSUE TITLE
question

### ISSUE THREAD

**Issue by thomas-void0** [xosuperpig/geek-nodejs#22]
老师您好，用node做纯后端的业务开发，在课程中似乎并没有提到。是因为不太会用node做纯后端的服务吗?通常在比如您这样体量的公司中node更多的是做什么业务呢？仅是ssr相关吗？

**Comment by zombieyang** [comment]
19年做课程那时候比较流行做ssr。现在做什么都挺常见的。

用来做纯后端服务也没什么不一样，课程里有用Node.js来写json接口。

**Comment by thomas-void0** [comment]
好的，了解了~thks
